{{- $root := . -}}
{{- $object := "deployment" -}}
{{- $globalMetadata := .Values.global.metadata -}}
{{- $globalSharedLabels := $globalMetadata.shared.labels -}}
{{- $globalObjectLabels := $globalMetadata.deployment.labels }}
{{- $globalSharedAnnotations := $globalMetadata.shared.annotations }}
{{- $globalObjectAnnotations := $globalMetadata.deployment.annotations }}
{{- $localMetadata := .Values.sampling_collector.metadata -}}
{{- $localSharedAnnotations := $localMetadata.shared.annotations -}}
{{- $localObjectAnnotations := $localMetadata.deployment.annotations -}}
{{- $localSharedLabels := $localMetadata.shared.labels -}}
{{- $localObjectLabels := $localMetadata.deployment.labels -}}
{{- $globalSubLabels := $globalMetadata.pod.labels }}
{{- $globalSubAnnotations := $globalMetadata.pod.annotations }}
{{- $localSubAnnotations := $localMetadata.pod.annotations -}}
{{- $localSubLabels := $localMetadata.pod.labels -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}-sampling-deployment
  namespace: {{ .Values.global.namespace }}
  labels: {{ tpl ( toYaml $globalSharedLabels | nindent 4) $ }}
{{- if $globalObjectLabels }}{{ tpl ( toYaml $globalObjectLabels | nindent 4) . }}{{- end }}
{{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
{{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
  annotations: {{ tpl ( toYaml $globalSharedAnnotations | nindent 4) $ }}
{{- if $globalObjectAnnotations }}{{ tpl ( toYaml $globalObjectAnnotations | nindent 4) . }}{{- end }}
{{- if $localSharedAnnotations }}{{ toYaml $localSharedAnnotations | nindent 4 }}{{- end }}
{{- if $localObjectAnnotations }}{{ toYaml $localObjectAnnotations | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels:
{{- toYaml .Values.sampling_collector.metadata.pod.labels | nindent 6 }}
{{- if not .Values.sampling_collector.specs.autoscaling.enable }}
  replicas: {{ .Values.sampling_collector.specs.autoscaling.defaultReplicaCount }}
{{- end }}
  {{- if .Values.global.rolloutStrategy }}
  strategy: {{ toYaml .Values.global.rolloutStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels: {{ tpl ( toYaml $globalSharedLabels | nindent 8) $ }}
    {{- if $globalSubLabels }}{{ tpl ( toYaml $globalSubLabels | nindent 8) . }}{{- end }}
    {{- if $localSharedLabels }}{{ toYaml $localSharedLabels | nindent 8 }}{{- end }}
    {{- if $localSubLabels }}{{ toYaml $localSubLabels | nindent 8 }}{{- end }}
      annotations: {{ tpl ( toYaml $globalSharedAnnotations | nindent 8 ) $ }}
    {{- if $globalSubAnnotations }}{{ tpl ( toYaml $globalSubAnnotations | nindent 8) . }}{{- end }}
    {{- if $localSharedAnnotations }}{{ toYaml $localSharedAnnotations | nindent 8 }}{{- end }}
    {{- if $localSubAnnotations }}{{ toYaml $localSubAnnotations | nindent 8 }}{{- end }}
    spec:
      volumes:
        - name: {{ .Values.sampling_collector.specs.volumes.serviceConfig.name }}
          configMap: 
            name: {{ .Values.sampling_collector.specs.volumes.serviceConfig.name }}
      containers:
        - name: "{{ .Values.global.name }}-{{ .Values.sampling_collector.metadata.name }}"
          image: "{{ .Values.sampling_collector.image.repository | default .Values.global.image.repository }}/{{ .Values.sampling_collector.image.name | default .Values.global.image.name }}:{{ .Values.sampling_collector.image.version | default .Values.global.image.version }}"
          imagePullPolicy: {{ .Values.sampling_collector.image.policy | default .Values.global.image.pullPolicy }}
          command: ["/otelcol-sampling","--config","/config/sampling-config.yml"]
          volumeMounts:
            - name: {{ .Values.sampling_collector.specs.volumes.serviceConfig.name }}
              mountPath: {{ .Values.sampling_collector.specs.volumes.serviceConfig.mountPath | quote}}
          {{- range .Values.sampling_collector.specs.volumes.extraVolumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
          {{- end }}
          {{- range .Values.sampling_collector.specs.volumes.extraSecretMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- if .Values.sampling_collector.env }}
          env:
          {{- range $key, $value := .Values.sampling_collector.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          ports:
          {{- range .Values.sampling_collector.specs.network.ports }}
            - containerPort: {{ .internalPort }}
              type: {{ .type }}
              name: {{ .name  }}
              protocol: {{ .protocol }}
          {{- end }}
          {{- if .Values.sampling_collector.specs.probe }}
{{ toYaml .Values.sampling_collector.specs.probe | trim | indent 10}}
          {{- end }}
          resources:
{{ toYaml .Values.sampling_collector.specs.resources | trim | indent 12 }}
