{{- $globalMetadata := .Values.global.metadata -}}
{{- $globalSharedLabels := $globalMetadata.shared.labels -}}
{{- $globalObjectLabels := $globalMetadata.hpa.labels }}
{{- $globalSharedAnnotations := $globalMetadata.shared.annotations }}
{{- $globalObjectAnnotations := $globalMetadata.hpa.annotations }}
{{- $localMetadata := .Values.sampling_collector.metadata -}}
{{- $localSharedAnnotations := $localMetadata.shared.annotations -}}
{{- $localObjectAnnotations := $localMetadata.hpa.annotations -}}
{{- $localSharedLabels := $localMetadata.shared.labels -}}
{{- $localObjectLabels := $localMetadata.hpa.labels -}}
{{- $localListenerIp := .Values.sampling_collector.specs.network.localListenerIp -}}
{{- if .Values.sampling_collector.specs.autoscaling.enable }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.global.name }}-sampling-hpa
  namespace: {{ .Values.global.namespace }}
  labels: {{ tpl ( toYaml $globalSharedLabels | nindent 4) $ }}
{{- if $globalObjectLabels }}{{ tpl ( toYaml $globalObjectLabels | nindent 4) . }}{{- end }}
{{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
{{- if $localObjectLabels }}{{ toYaml $localObjectLabels | nindent 4 }}{{- end }}
  annotations: {{ tpl ( toYaml $globalSharedAnnotations | nindent 4) $ }}
{{- if $globalObjectAnnotations }}{{ tpl ( toYaml $globalObjectAnnotations | nindent 4) . }}{{- end }}
{{- if $localSharedAnnotations }}{{ toYaml $localSharedAnnotations | nindent 4 }}{{- end }}
{{- if $localObjectAnnotations }}{{ toYaml $localObjectAnnotations | nindent 4 }}{{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.global.name }}-sampling-deployment
  minReplicas: {{ .Values.sampling_collector.specs.autoscaling.minReplicas }} 
  maxReplicas: {{ .Values.sampling_collector.specs.autoscaling.maxReplicas }} 
  metrics:
  {{- with .Values.sampling_collector.specs.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.sampling_collector.specs.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
{{- end }}